# Generated by Django 3.1.3 on 2020-12-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=10)),
                ('sex', models.CharField(default='male', max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('pro', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
            ],
        ),
    ]
